// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Contact Module const
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

//Auth const
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNIN_GOOGLE_USER = "SIGNIN_GOOGLE_USER";
export const SIGNIN_GOOGLE_USER_SUCCESS = "SIGNIN_GOOGLE_USER_SUCCESS";
export const SIGNIN_FACEBOOK_USER = "SIGNIN_FACEBOOK_USER";
export const SIGNIN_FACEBOOK_USER_SUCCESS = "SIGNIN_FACEBOOK_USER_SUCCESS";
export const SIGNIN_TWITTER_USER = "SIGNIN_TWITTER_USER";
export const SIGNIN_TWITTER_USER_SUCCESS = "SIGNIN_TWITTER_USER_SUCCESS";
export const SIGNIN_GITHUB_USER = "SIGNIN_GITHUB_USER";
export const SIGNIN_GITHUB_USER_SUCCESS = "signin_github_user_success";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const INIT_URL = "INIT_URL";

/*SCREEN*/
export const SCREEN_NEXT = "SCREEN_NEXT";
export const SET_NEXT_VALUE = "SET_NEXT_VALUE";

/* PROJECTS */
export const GET_ALL_THREADS = "GET_ALL_THREADS";
export const GET_THREADS = "GET_THREADS";
export const THREADS_ADD_SUCCESS = "THREADS_ADD_SUCCESS";
export const PROJECTS_GET_ITEMS = "PROJECTS_GET_ITEMS";
export const PROJECTS_GET_ALL_ITEMS = "PROJECTS_GET_ALL_ITEMS";
export const PROJECTS_ADD_ITEM = "PROJECTS_ADD_ITEM";
export const PROJECTS_EDIT_ITEM = "PROJECTS_EDIT_ITEM";
export const PROJECTS_DELETE_ITEM = "PROJECTS_DELETE_ITEM";
export const PROJECTS_LOAD_ITEM = "PROJECTS_LOAD_ITEM";
export const PROJECTS_LOADING = "PROJECTS_LOADING";
export const PROJECTS_ADD_SUCCESS = "PROJECTS_ADD_SUCCESS";
export const PROJECTS_ADD_FAIL = "PROJECTS_ADD_FAIL";
export const PROJECTS_EDIT_FAIL = "PROJECTS_EDIT_FAIL";
export const PROJECTS_UPDATE = "PROJECTS_UPDATE";
export const PROJECTS_CATEGORY_LOAD_ITEM = "PROJECTS_CATEGORY_LOAD_ITEM";
export const PROJECTS_SUBCATEGORY_LOAD_ITEM = "PROJECTS_SUBCATEGORY_LOAD_ITEM";
export const PROJECTS_OWNER_LOAD_ONE = "PROJECTS_OWNER_LOAD_ONE";
export const PROJECTS_OWNER_LOAD_ITEM = "PROJECTS_OWNER_LOAD_ITEM";
export const PROJECTS_INVITE_AUTHOR = "PROJECTS_INVITE_AUTHOR";
export const PROJECTS_AUTHOR_LOAD_ITEMS = "PROJECTS_AUTHOR_LOAD_ITEMS";
export const PROJECT_AUTHOR_LOAD = "PROJECT_AUTHOR_LOAD";
export const PROJECTS_STUDENT_LOAD = "PROJECTS_STUDENT_LOAD";
export const PROJECTS_STUDENT_LOAD_ALL = "PROJECTS_STUDENT_LOAD_ALL";
export const PROJECTS_STUDENT_LOAD_MAIL = "PROJECTS_STUDENT_LOAD_MAIL";
export const PROJECTS_GET_ALL_SUBMITTED = "PROJECTS_GET_ALL_SUBMITTED";
export const PROJECTS_ASSOCIATE = "PROJECTS_ASSOCIATE";
export const ANNULATION_PROJECTS_ASSOCIATION =
  "ANNULATION_PROJECTS_ASSOCIATION";
export const PROJECTS_ASSOCIATE_LOAD = "PROJECTS_ASSOCIATE_LOAD";
export const INVITE_EMAIL_PROJECT = "INVITE_EMAIL_PROJECT";
export const EMAIL_REFUSED_PROJECT = "EMAIL_REFUSED_PROJECT";
export const PROJECTS_SEARCH_ITEMS = "PROJECTS_SEARCH_ITEMS";
export const PROJECTS_INIT_SEARCH = "PROJECTS_INIT_SEARCH";
export const PROJECTS_UPDATE_SEARCH_TEXT = "PROJECTS_UPDATE_SEARCH_TEXT";
export const PROJECT_UPDATE_PRICE = "PROJECT_UPDATE_PRICE";
export const PROJECT_SUBMIT_EMAILS = "PROJECT_SUBMIT_EMAILS";
export const PROJECTS_STUDENTS_INVITED_LOAD = "PROJECTS_STUDENTS_INVITED_LOAD";
export const PROJECTS_HELPER_LOAD_ALL = "PROJECTS_HELPER_LOAD_ALL";
export const PROJECTS_HELPER_LOAD = "PROJECTS_HELPER_LOAD";
export const PROJECTS_STUDENT_PAYED_LOAD = "PROJECTS_STUDENT_PAYED_LOAD";
export const PROJECTS_INIT_CREATE = "PROJECTS_INIT_CREATE";
export const PROJECT_STUDENT_INIT = "PROJECT_STUDENT_INIT";
export const PROJECTS_GET_LAST_ITEMS = "PROJECTS_GET_LAST_ITEMS";
export const PROJECTS_GET_MOST_VIEWED = "PROJECTS_GET_MOST_VIEWED";
export const PROJECTS_GET_UNAVOIDABLES = "PROJECTS_GET_UNAVOIDABLES";
export const PROJECTS_DELETE_VIDEO = "PROJECTS_DELETE_VIDEO";
export const AWS_PROJECTS_LOAD_ITEM = "AWS_PROJECTS_LOAD_ITEM";
export const PROJECTS_GET_EXPERT_ARCHIVES = "PROJECTS_GET_EXPERT_ARCHIVES";
export const PROJECTS_GET_STUDENT_ARCHIVES = "PROJECTS_GET_STUDENT_ARCHIVES";
export const PROJECTS_GET_HELPER_ARCHIVES = "PROJECTS_GET_HELPER_ARCHIVES";
export const PROJECTS_GET_ASSISTANT_ARCHIVES =
  "PROJECTS_GET_ASSISTANT_ARCHIVES";
export const PROJECT_AUTHORS_LOAD_ITEMS = "PROJECT_AUTHORS_LOAD_ITEMS"

/*TAGS*/
export const TAGS_ADD = "TAGS_ADD";
export const TAGS_GET_ALL = "TAGS_GET_ALL";
export const TAGS_INIT = "TAGS_INIT";

/*EXERCICES*/
export const EXERCICES_GET_ITEMS = "EXERCICES_GET_ITEMS";
export const EXERCICES_ADD_ITEM = "EXERCICES_ADD_ITEM";
export const EXERCICES_EDIT_ITEM = "EXERCICES_EDIT_ITEM";
export const EXERCICES_DELETE_ITEM = "EXERCICES_EDIT_ITEM";
export const EXERCICES_LOAD_ITEM = "EXERCICES_LOAD_ITEM";
export const EXERCICES_LOAD_FAIL = "EXERCICES_LOAD_FAIL";
export const EXERCICES_ADD_SUCCESS = "EXERCICES_ADD_SUCCESS";
export const EXERCICES_ADD_FAIL = "EXERCICES_ADD_FAIL";
export const EXERCICES_EDIT_FAIL = "EXERCICES_EDIT_FAIL";
export const EXERCICES_UPDATED = "EXERCICES_UPDATED";
export const EXERCICES_GET_ITEMS_ORDERED = "EXERCICES_GET_ITEMS_ORDERED";
export const EXERCICES_DELETE_VIDEO = "EXERCICES_DELETE_VIDEO";
export const EXERCISE_LOAD_ANSWER = "EXERCISE_LOAD_ANSWER";
export const EXERCISE_UPDATE_ANSWER = "EXERCISE_UPDATE_ANSWER";

/* USER */
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

/* AUTHENTIFICATION */
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

/* REGISTER */
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

/*Gestion des errors*/
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

/*UPLOAD FILE*/
export const LOADING_FILE = "LOADING_FILE";

/* VIDEO FILE */
export const VIDEO_SUCCESS = "VIDEO_SUCCESS";
export const VIDEO_DELETE = "VIDEO_DELETE";

/*CATEGORY*/
export const CATEGORIES_GET_ITEMS = "CATEGORIES_GET_ITEMS";

/*OPINION*/
export const OPINIONS_ADD_SUCCESS = "OPINIONS_ADD_SUCCESS";
export const OPINION_LOAD_ITEM = "OPINION_LOAD_ITEM";

/* USER */
export const USER_GET_ITEMS = "USER_GET_ITEMS";
export const USER_UPDATE_ITEM = "USER_UPDATE_ITEM";
export const USER_PROFILE_UPDATE_ITEM = "USER_PROFILE_UPDATE_ITEM";
export const ACTIVE_USER = "ACTIVE_USER";
export const USER_INFO_PROFILE = "USER_INFO_PROFILE";
export const OWNER_INFO_PROFILE = "OWNER_INFO_PROFILE";
export const USER_FOLLOWER = "USER_FOLLOWER";
export const ANNULATION_FOLLOW = "ANNULATION_FOLLOW";
export const USER_FOLLOWED = "USER_FOLLOWED";
export const PASSWORD_FORGOT = "PASSWORD_FORGOT";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const USER_IBAN = "USER_IBAN";
export const USER_EARNINGS = "USER_EARNINGS";

/* SUBCATEGORIES */
export const SUBCATEGORIES_GET_ITEMS = "SUBCATEGORIES_GET_ITEMS";
export const SUBCATEGORIES_ALL_GET_ITEMS = "SUBCATEGORIES_ALL_GET_ITEMS";
